[tool.poetry]
name = "rest api"
version = "0.1.0"
description = "-"
authors = ["Vikka777 <vikki.mrrr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sphinx = "^7.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
